import com.vanniktech.maven.publish.SonatypeHost

plugins {
    `java-library`
    id("com.vanniktech.maven.publish") version "0.30.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    // HTTP Client
    api("com.squareup.okhttp3:okhttp:4.12.0")

    // JSON Processing
    api("com.fasterxml.jackson.core:jackson-databind:2.17.0")

    // xxHash32 for percentage-based rollouts (compatible with JavaScript xxhashjs)
    implementation("org.lz4:lz4-java:1.8.0")

    // Null-safety annotations for Kotlin interop
    api("org.jetbrains:annotations:24.1.0")

    // Logging facade
    api("org.slf4j:slf4j-api:2.0.12")

    // Testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    testRuntimeOnly("org.slf4j:slf4j-simple:2.0.12")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(listOf("-Xlint:all", "-Xlint:-processing"))
}

tasks.javadoc {
    options {
        (this as StandardJavadocDocletOptions).apply {
            addStringOption("Xdoclint:none", "-quiet")
            encoding = "UTF-8"
        }
    }
}

// Generate TgglVersion.java from project version
val generateVersion = tasks.register("generateVersionFile") {
    val outputDir = layout.buildDirectory.dir("generated/sources/version/java/main")
    val projectVersion = project.version.toString()

    inputs.property("version", projectVersion)
    outputs.dir(outputDir)

    doLast {
        val versionFile = outputDir.get().file("io/tggl/TgglVersion.java").asFile
        versionFile.parentFile.mkdirs()
        versionFile.writeText(
            """
            |package io.tggl;
            |
            |/**
            | * Shared version constant for the Tggl Java SDK.
            | * This file is generated by the build — do not edit manually.
            | */
            |public final class TgglVersion {
            |
            |    /**
            |     * The current SDK version string.
            |     */
            |    public static final String VERSION = "$projectVersion";
            |
            |    private TgglVersion() {
            |        // Utility class
            |    }
            |}
            """.trimMargin()
        )
    }
}

sourceSets {
    main {
        java {
            srcDir(generateVersion.map { layout.buildDirectory.dir("generated/sources/version/java/main") })
        }
    }
}

tasks.withType<JavaCompile> {
    dependsOn(generateVersion)
}

// Skip signing when keys are not available (e.g. local development)
tasks.withType<Sign>().configureEach {
    onlyIf {
        project.findProperty("signingInMemoryKey") != null ||
            System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKey") != null
    }
}

mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)
    signAllPublications()

    coordinates("io.tggl", "tggl-client", project.version.toString())

    pom {
        name.set("Tggl Java Client")
        description.set("Java SDK for Tggl feature flags - works with both Java and Kotlin")
        url.set("https://github.com/Tggl/java-tggl-client")

        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
            }
        }

        developers {
            developer {
                id.set("tggl")
                name.set("Tggl")
                email.set("support@tggl.io")
            }
        }

        scm {
            connection.set("scm:git:git://github.com/Tggl/java-tggl-client.git")
            developerConnection.set("scm:git:ssh://github.com/Tggl/java-tggl-client.git")
            url.set("https://github.com/Tggl/java-tggl-client")
        }
    }
}
